-- MySQL Script generated by MySQL Workbench
-- Tue May 23 17:11:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concentdb
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema concentdb
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concentdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `concentdb` ;

-- -----------------------------------------------------
-- Table `concentdb`.`TabUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentdb`.`TabUsuario` (
  `idTabUsuario` INT NOT NULL AUTO_INCREMENT,
  `TabUsuarioNome` VARCHAR(255) NOT NULL,
  `TabUsuarioCpf` VARCHAR(11) NOT NULL,
  `TabUsuarioTipo` INT NOT NULL DEFAULT 1 COMMENT 'Tipo do Usuario: 0 - Admin | 1 - Cliente',
  `TabUsuarioMesa` INT NULL,
  PRIMARY KEY (`idTabUsuario`),
  UNIQUE INDEX `TabUsuarioCpf_UNIQUE` (`TabUsuarioCpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentdb`.`TabProdutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentdb`.`TabProdutos` (
  `idTabProdutos` INT NOT NULL AUTO_INCREMENT,
  `TabProdutosNome` VARCHAR(255) NOT NULL,
  `TabProdutosValor` DECIMAL NOT NULL,
  `TabProdutosGrupo` INT NOT NULL,
  `TabProdutosTempoPreparo` INT NULL,
  `TabProdutosAtivo` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1 - Ativo | 0 - Inativo',
  PRIMARY KEY (`idTabProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentdb`.`TabPedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentdb`.`TabPedidos` (
  `idTabPedidos` INT NOT NULL AUTO_INCREMENT,
  `TabPedidosMesa` VARCHAR(45) NOT NULL,
  `TabPedidosStatus` INT NOT NULL DEFAULT 0 COMMENT '0 - Pedido Realizado | 1 - Pedido Confirmado | 2 - Pedido Pronto | 3 - Pedido Concluido',
  `TabPedidosIdUsuario` INT NOT NULL,
  PRIMARY KEY (`idTabPedidos`),
  INDEX `TabPedidosIdUsuario_idx` (`TabPedidosIdUsuario` ASC) VISIBLE,
  CONSTRAINT `TabPedidosIdUsuario`
    FOREIGN KEY (`TabPedidosIdUsuario`)
    REFERENCES `concentdb`.`TabUsuario` (`idTabUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concentdb`.`TabPedidosItens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concentdb`.`TabPedidosItens` (
  `idTabPedidosItens` INT NOT NULL,
  `TabPedidosItensIdProduto` INT NOT NULL,
  `TabPedidosItensQuantidade` INT NOT NULL,
  `TabPedidosItensIdPedido` INT NOT NULL,
  PRIMARY KEY (`idTabPedidosItens`),
  INDEX `TabPedidosItensIdProduto_idx` (`TabPedidosItensIdProduto` ASC) VISIBLE,
  INDEX `TabPedidosItensIdPedido_idx` (`TabPedidosItensIdPedido` ASC) VISIBLE,
  CONSTRAINT `TabPedidosItensIdProduto`
    FOREIGN KEY (`TabPedidosItensIdProduto`)
    REFERENCES `concentdb`.`TabProdutos` (`idTabProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TabPedidosItensIdPedido`
    FOREIGN KEY (`TabPedidosItensIdPedido`)
    REFERENCES `concentdb`.`TabPedidos` (`idTabPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
